server:
  host: localhost
  port: 8080

spring:
  profiles:
    active: dev
  application-name: bards-respect-back
  datasource:
    url: jdbc:postgresql://postgres:5432/bardsdb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    clean-disabled: true